/*
 * This file is generated by jOOQ.
 */
package org.autotesting.database.tables.records;


import org.autotesting.database.tables.Currency;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CurrencyRecord extends UpdatableRecordImpl<CurrencyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.currency.currency_id</code>.
     */
    public void setCurrencyId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.currency.currency_id</code>.
     */
    public Integer getCurrencyId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.currency.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.currency.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CurrencyRecord
     */
    public CurrencyRecord() {
        super(Currency.CURRENCY);
    }

    /**
     * Create a detached, initialised CurrencyRecord
     */
    public CurrencyRecord(Integer currencyId, String title) {
        super(Currency.CURRENCY);

        setCurrencyId(currencyId);
        setTitle(title);
        resetChangedOnNotNull();
    }
}
