/*
 * This file is generated by jOOQ.
 */
package org.autotesting.database;


import org.autotesting.database.tables.Account;
import org.autotesting.database.tables.Candle;
import org.autotesting.database.tables.Currency;
import org.autotesting.database.tables.Trade;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.candle</code>.
     */
    public static final Candle CANDLE = Candle.CANDLE;

    /**
     * The table <code>public.currency</code>.
     */
    public static final Currency CURRENCY = Currency.CURRENCY;

    /**
     * The table <code>public.trade</code>.
     */
    public static final Trade TRADE = Trade.TRADE;
}
